"""Prompts for the analytics agent.

Increment 2 wires this into a LangGraph graph. The graph is mechanical; the
routing prompt is the part that decides whether the product works, so it lives
here on its own and gets its own eval cases.

    SYSTEM_PROMPT is written by hand. See the TODO below.
"""

from __future__ import annotations

from enum import StrEnum


class Route(StrEnum):
    """Where a question goes after the router node.

    Keep this list small. Every route is a branch the eval set has to cover, and
    a router with six options is a router you cannot debug.
    """

    SQL = "sql"
    """Answerable by querying the marts. Numbers, rates, counts, comparisons."""

    SEMANTIC = "semantic"
    """Answerable from match notes / narrative via pgvector. Fuzzy, descriptive."""

    HYBRID = "hybrid"
    """Needs both: a number from SQL plus context that only prose carries."""

    REFUSE = "refuse"
    """Not answerable from this data at all. Saying so is a correct answer."""


# Rendered into SYSTEM_PROMPT at request time. Generated by schema_context.py
# from the dbt manifest (descriptions) plus Postgres (every live column), so the
# agent's view of the schema can never drift from the warehouse.
SCHEMA_CONTEXT_PLACEHOLDER = "{schema_context}"

# Marks a section Kyle has not written yet. render_system_prompt() refuses to
# render while any section still holds it, so a half-written prompt can never
# reach a model by accident.
UNWRITTEN = "TODO"


# ============================================================================
#  TODO(kyle): write SYSTEM_PROMPT, one section at a time.
#
#  WHY THIS ONE IS YOURS
#
#  This prompt is where the project's two layers meet. It is also the single
#  artifact an interviewer can read in 60 seconds and tell whether you have
#  actually built an agent or just called an LLM. Do not let a model write it.
#
#  THE SHAPE
#
#  Seven sections, each wrapped in an XML-style tag when rendered. One job per
#  section means each job can be tested and changed on its own -- the same
#  "change one thing at a time" rule as sql/investigations/.
#
#    <role> <data_contract> <routing> <grounding> <refusal> <style> <schema>
#
#  `deuce prompt` prints the rendered prompt with each section's size, and
#  lists the sections still unwritten. <schema> is generated: never edit it.
#
#  SETTLED ALREADY
#
#  - Schema: ALL live columns go in, not descriptions only. Measured: 313
#    columns at ~6,500 tokens, against 129 columns at ~5,200 with descriptions
#    only. The extra ~1,300 tokens buy the 184 columns a model would otherwise
#    have to invent.
#  - The agent shows its SQL. Every answer is auditable; so is every mistake.
#
#  STILL YOURS TO SETTLE
#
#  - Router inside this prompt, or a separate cheap classifier call? One call
#    is faster and keeps context. Two are independently evaluable and can run
#    a small model on the routing. You can only measure what you can isolate.
#
#  START SMALLER THAN YOU THINK. Write <role>, <routing> and <grounding> for
#  the SQL route first. Run the 16 cases in tennis-questions.yml. Let the
#  failures tell you what <refusal> and <style> need to say. A prompt written
#  against observed failures beats one written against imagined ones.
# ============================================================================


# ----------------------------------------------------------------------------
#  <role> -- who answers, for whom.
#
#  - The reader is tennis-literate. The prompt should say so, or the model
#    explains what a break point is.
#  - What is the agent FOR? "Answer questions" is not a purpose. "Turn charted
#    match data into a scouting claim with its evidence" is.
#  - One or two sentences. A long role section is a symptom of rules that
#    belong in another section.
# ----------------------------------------------------------------------------
ROLE = UNWRITTEN


# ----------------------------------------------------------------------------
#  <data_contract> -- what the data can and cannot support.
#
#  docs/data-trust.md in compressed form. Its tiers (A verified, B exact, C
#  caveated, D untrustworthy, absent) are the grounding contract. "An answer
#  inherits the lowest tier of its inputs" is the one sentence it must carry.
#
#  Decide how much goes HERE and how much stays in column descriptions (which
#  <schema> already carries). A caveat stated in both places will drift; a
#  caveat in neither is lost. Suggestion: tiers and the inheritance rule here,
#  per-column caveats in the descriptions, and one line telling the model to
#  state the caveat it finds in a column description.
#
#  The caveats the marts already carry, for reference:
#    parsed rates          parse_confidence era; never compare across silently
#    mart_rally_shape      compare players by SLOPE, never by level
#    mart_pressure_index   leverage = a typical server, not this one; tiebreaks NULL
#    mart_player_style     under 20 matches is thin; watch direction_charted_rate
#    mart_matchup          delta includes career change + opponent quality;
#                          77% of pairs have one match
# ----------------------------------------------------------------------------
DATA_CONTRACT = UNWRITTEN


# ----------------------------------------------------------------------------
#  <routing> -- pick a Route.
#
#  The hard cases SOUND semantic but are not:
#
#    "Who's the biggest first-strike player?"      -> SQL (win rate, <=4 shots)
#    "Does Alcaraz look nervous on break points?"  -> REFUSE (not in the data)
#    "Why did Sinner lose that match?"             -> HYBRID, or REFUSE?
#
#  That third one is the interesting one. Decide where the line is and say it
#  explicitly -- vague instructions produce vague routing.
#
#  SEMANTIC and HYBRID have nothing to retrieve from until Increment 3. Decide
#  what the router does with them NOW: route anyway and let the next node
#  refuse, or never pick them yet? Write the decision down either way.
# ----------------------------------------------------------------------------
ROUTING = UNWRITTEN


# ----------------------------------------------------------------------------
#  <grounding> -- every answer cites its evidence.
#
#  The brief's promise is "grounded, cited answers". This is the section that
#  has to make it true. Name the parts of an answer, so the eval can check
#  each one: the claim, the number, n, the filter applied, the SQL, the caveat.
#  A fixed answer shape is what makes grounding scoreable.
# ----------------------------------------------------------------------------
GROUNDING = UNWRITTEN


# ----------------------------------------------------------------------------
#  <refusal> -- say no well.
#
#  Under-supported is worse than unanswered. Put NUMBERS here, not adjectives:
#  tennis-questions.yml says "if N < 20 say the sample is thin".
#
#  The strongest refusal names the CLOSEST answerable question and answers
#  that. guard-01 (serve speed) expects exactly this: speed is not charted,
#  direction is. docs/data-trust.md "Not in the data at all" is the list.
# ----------------------------------------------------------------------------
REFUSAL = UNWRITTEN


# ----------------------------------------------------------------------------
#  <style> -- speak tennis.
#
#  "62% of second serves to the T" is data. "She goes to the body under
#  pressure and it's readable" is an answer. Say how to turn the first into
#  the second WITHOUT dropping the number -- the number is the evidence.
# ----------------------------------------------------------------------------
STYLE = UNWRITTEN


SECTIONS: dict[str, str] = {
    "role": ROLE,
    "data_contract": DATA_CONTRACT,
    "routing": ROUTING,
    "grounding": GROUNDING,
    "refusal": REFUSAL,
    "style": STYLE,
}


def unwritten_sections(sections: dict[str, str] = SECTIONS) -> list[str]:
    """Names of the sections that still hold the UNWRITTEN marker."""
    return [name for name, text in sections.items() if text.strip() == UNWRITTEN]


def assemble(sections: dict[str, str] = SECTIONS) -> str:
    """Wrap each section in its tag. <schema> goes last, as a placeholder."""
    parts = [f"<{name}>\n{text.strip()}\n</{name}>" for name, text in sections.items()]
    parts.append(f"<schema>\n{SCHEMA_CONTEXT_PLACEHOLDER}\n</schema>")
    return "\n\n".join(parts)


def render_system_prompt(
    schema_context: str, sections: dict[str, str] = SECTIONS, allow_unwritten: bool = False
) -> str:
    """The prompt a model receives. Refuses while any section is unwritten.

    `allow_unwritten=True` is for `deuce prompt`, which shows the draft.
    """
    missing = unwritten_sections(sections)
    if missing and not allow_unwritten:
        raise ValueError(f"SYSTEM_PROMPT sections not written yet: {', '.join(missing)}")
    # str.replace, not str.format: the schema and the prose may contain braces.
    return assemble(sections).replace(SCHEMA_CONTEXT_PLACEHOLDER, schema_context)


SYSTEM_PROMPT = assemble()


ROUTER_EXAMPLES: list[tuple[str, Route]] = [
    # Few-shot pairs for the router. Fill these from the cases that actually
    # fail once the agent runs -- not from guesses.
    # ("Who's the biggest first-strike player on tour?", Route.SQL),
]
